### ISSUE TITLE
React 17 support?

### ISSUE THREAD

**Issue by bsmith-self** [BananaWanted/ab-testing#53]
The `react-ab-testing` package has this peer dependency:
```json
"react": "^16.0.0"
```

Based on the fact that the root package has:
```json
"@types/react": "^17.0.2",
```

I'm guessing the requirement for 16 is unintentional?

**Comment by ZigZagT** [comment]
The version numbers in peer dependency don't matter much. It won't impose any real restrictions on the user side. 

For instance, we use react17 in the [root package.json](https://github.com/appannie/ab-testing/blob/master/package.json#L32) file for testing.

**Comment by bsmith-self** [comment]
But they still matter, because otherwise people will wonder if there's an incompatibility and might hold off on an upgrade out of caution, or otherwise go down a rabbit-hole trying to research whether or not the upgrade is safe to do. It's worth keeping them up to date as much as possible.

To get specific: I spent hours researching this, and then my team spent hours QAing the app post-upgrade, because we didn't have an official answer on compatibility.
